name: test-semantic-release
run-name: ${{ github.actor }} is learning semantic release
on:
  pull_request:
    types: [ closed ]
jobs:
  tag-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/changelog
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_REPOSITORY_SECRET }}
        GH_TOKEN: ${{ secrets.TEST_REPOSITORY_SECRET }}

